from dataloader.DataLoader import data_loader as DataLoader
from dataloader.DataLoader_prompt import data_loader as DataLoader_prompt
from dataloader.DataLoader_prompt_front import data_loader as DataLoader_prompt_front
